[project]
name = "chat-try"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "prompt-toolkit>=3.0.50",
    "requests>=2.32.3",
    "rich>=13.9.4",
]
