[project]
dependencies = [
  "logging>=0.4.9.6",
  "prompt-toolkit>=3.0.50",
  "requests>=2.32.3",
  "rich>=13.9.4",
  "tenacity>=9.0.0",
]
description = "Ollama chat playground with multiple AI characters"
name = "chat-try"
readme = "README.md"
requires-python = ">=3.13"
version = "0.1.0"
